### ISSUE TITLE
build fails in MacOS 13.1

### ISSUE THREAD

**Issue by vladstudio** [nobu-g/DebounceMac#3]
When I try `swift build -c release` I get

```
error: 'debouncemac': Invalid manifest
/Users/vlad/Temp/DebounceMac/Package.swift:3:8: error: no such module 'PackageDescription'
import PackageDescription
       ^
```

MacOS 13.1 (22C65), no XCode installed.

**Comment by nobu-g** [comment]
I could not reproduce the error in my environment (macOS 13.1, Xcode installed).

Try to install Xcode or Xcode Command Line Tools with `sudo xcode-select --install`.
If this doesn't work, try to switch the Xcode path with `sudo xcode-select --switch /your/path/to/Xcode` (https://forums.kodeco.com/t/server-error-no-such-module-packagedescription/177438).
FYI, my Xcode path is `/Applications/Xcode.app/Contents/Developer`.

**Comment by vladstudio** [comment]
I think that means that I need to have xcode installed (which I don't :-) ) 
command line tools (xcode-select --install) were already installed. I'll try to install xcode and repeat. thanks.

**Comment by vladstudio** [comment]
hey! I installed xcode and executed `sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer` and this seemed to help! 

P.S. is it not an easy process to provide binaries or packages for homebrew? I don't mind installing xcode only to install other apps, but not too often :-)

**Comment by nobu-g** [comment]
That's good!
I've updated the build instructions to install Xcode. And I will release pre-built binaries when I have some time :)
